export namespace Flag {
  export const OPENDOC_AUTO_SHARE = truthy("OPENDOC_AUTO_SHARE")
  export const OPENDOC_GIT_BASH_PATH = process.env["OPENDOC_GIT_BASH_PATH"]
  export const OPENDOC_CONFIG = process.env["OPENDOC_CONFIG"]
  export const OPENDOC_CONFIG_DIR = process.env["OPENDOC_CONFIG_DIR"]
  export const OPENDOC_CONFIG_CONTENT = process.env["OPENDOC_CONFIG_CONTENT"]
  export const OPENDOC_DISABLE_AUTOUPDATE = truthy("OPENDOC_DISABLE_AUTOUPDATE")
  export const OPENDOC_DISABLE_PRUNE = truthy("OPENDOC_DISABLE_PRUNE")
  export const OPENDOC_DISABLE_TERMINAL_TITLE = truthy("OPENDOC_DISABLE_TERMINAL_TITLE")
  export const OPENDOC_PERMISSION = process.env["OPENDOC_PERMISSION"]
  export const OPENDOC_DISABLE_DEFAULT_PLUGINS = truthy("OPENDOC_DISABLE_DEFAULT_PLUGINS")
  export const OPENDOC_DISABLE_LSP_DOWNLOAD = truthy("OPENDOC_DISABLE_LSP_DOWNLOAD")
  export const OPENDOC_ENABLE_EXPERIMENTAL_MODELS = truthy("OPENDOC_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENDOC_DISABLE_AUTOCOMPACT = truthy("OPENDOC_DISABLE_AUTOCOMPACT")
  export const OPENDOC_DISABLE_MODELS_FETCH = truthy("OPENDOC_DISABLE_MODELS_FETCH")
  export const OPENDOC_DISABLE_CLAUDE_CODE = truthy("OPENDOC_DISABLE_CLAUDE_CODE")
  export const OPENDOC_DISABLE_CLAUDE_CODE_PROMPT =
    OPENDOC_DISABLE_CLAUDE_CODE || truthy("OPENDOC_DISABLE_CLAUDE_CODE_PROMPT")
  export const OPENDOC_DISABLE_CLAUDE_CODE_SKILLS =
    OPENDOC_DISABLE_CLAUDE_CODE || truthy("OPENDOC_DISABLE_CLAUDE_CODE_SKILLS")
  export const OPENDOC_FAKE_VCS = process.env["OPENDOC_FAKE_VCS"]
  export const OPENDOC_CLIENT = process.env["OPENDOC_CLIENT"] ?? "cli"
  export const OPENDOC_SERVER_PASSWORD = process.env["OPENDOC_SERVER_PASSWORD"]
  export const OPENDOC_SERVER_USERNAME = process.env["OPENDOC_SERVER_USERNAME"]

  // Experimental
  export const OPENDOC_EXPERIMENTAL = truthy("OPENDOC_EXPERIMENTAL")
  export const OPENDOC_EXPERIMENTAL_FILEWATCHER = truthy("OPENDOC_EXPERIMENTAL_FILEWATCHER")
  export const OPENDOC_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("OPENDOC_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENDOC_EXPERIMENTAL_ICON_DISCOVERY =
    OPENDOC_EXPERIMENTAL || truthy("OPENDOC_EXPERIMENTAL_ICON_DISCOVERY")
  export const OPENDOC_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("OPENDOC_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENDOC_ENABLE_EXA =
    truthy("OPENDOC_ENABLE_EXA") || OPENDOC_EXPERIMENTAL || truthy("OPENDOC_EXPERIMENTAL_EXA")
  export const OPENDOC_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("OPENDOC_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const OPENDOC_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("OPENDOC_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENDOC_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("OPENDOC_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENDOC_EXPERIMENTAL_OXFMT = OPENDOC_EXPERIMENTAL || truthy("OPENDOC_EXPERIMENTAL_OXFMT")
  export const OPENDOC_EXPERIMENTAL_LSP_TY = truthy("OPENDOC_EXPERIMENTAL_LSP_TY")
  export const OPENDOC_EXPERIMENTAL_LSP_TOOL = OPENDOC_EXPERIMENTAL || truthy("OPENDOC_EXPERIMENTAL_LSP_TOOL")
  export const OPENDOC_EXPERIMENTAL_PLAN_MODE = OPENDOC_EXPERIMENTAL || truthy("OPENDOC_EXPERIMENTAL_PLAN_MODE")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
